title: "Fragments on AI, Ethics & Elsewhere"
description: "A grad student's notebook on AI ethics, art, and travel."
theme: minima

# Optional nice things:
author: "Ace Asim"
timezone: "Beijing Right Now"

# Navigation links (you can tweak later)
header_pages:
  - index.md
